title: Hire Miguel Diaz Zelaya
author: Miguel Diaz Zelaya  
email: business.mdiaz15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is to share the employment history and resume for Miguel Diaz Zelaya. 
  Feel free to use the contact information provided to reach out to discuss any employment opportunities.
# social links
blogger_username: https://hiremigueldiazzelaya.blogspot.com/

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
